/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.file.Path;
import java.util.concurrent.atomic.AtomicReference;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonBar;
import javafx.scene.control.ButtonType;
import javafx.scene.control.Dialog;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.control.SplitPane;
import javafx.scene.control.TextArea;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyEvent;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Region;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.stage.DirectoryChooser;
import java.io.File;

/**
 * JavaFX アプリケーションのエントリポイント。
 * シンプルなチャット UI を構築し、`ChatInteractor` を介してメッセージ送受信を行う。
 */
public class App extends Application {
    private static final String APP_NAME = "MyAIAgent2";

    /**
     * Java アプリケーションのメインメソッド。JavaFX を起動する。
     *
     * @param args コマンドライン引数
     */
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    /**
     * JavaFX のステージを初期化してチャット UI を配置する。
     *
     * @param stage メインステージ
     */
    public void start(Stage stage) {
        Logger log = LoggerFactory.getLogger(App.class);
        Path workDir = Path.of(System.getProperty("user.dir"));
        ConversationStore conversationStore = new JsonConversationStore(workDir);
        ChatService chatService = ChatServiceFactory.createDefault();
        // 初期作業ディレクトリを設定して UI に表示できるようにしておく
        chatService.setWorkingDirectory(workDir);

        // 起動時は必ず新規セッションから開始する（初期ディレクトリをセッションに保存）
        ConversationSession initial = conversationStore.createNewSession(workDir.toString());
        ChatInteractor initialInteractor = new ChatInteractor(
            chatService,
            new DefaultManualToolExecutor(),
            conversationStore,
            initial.sessionId());
        AtomicReference<ChatInteractor> interactorRef = new AtomicReference<>(initialInteractor);

        ChatDisplayPane chatHistory = new ChatDisplayPane();
        chatHistory.updateTranscript(interactorRef.get().getTranscript());

        ListView<SessionSummary> sessionList = new ListView<>();
        sessionList.setPrefWidth(220);

        Runnable[] refreshSessionsRef = new Runnable[1];
        refreshSessionsRef[0] = () -> {
            sessionList.getItems().setAll(conversationStore.listSessions());
            String currentSessionId = interactorRef.get().getCurrentSessionId();
            if (currentSessionId.isBlank()) {
                return;
            }
            for (SessionSummary summary : sessionList.getItems()) {
                if (currentSessionId.equals(summary.sessionId())) {
                    sessionList.getSelectionModel().select(summary);
                    break;
                }
            }
        };

        // 作業ディレクトリ表示ラベルを先に用意しておく（セッション切替時に更新するため）
        Label baseDirLabel = new Label();

        Button newChatButton = new Button("+ 新規");
        newChatButton.setOnAction(event -> {
            ConversationSession created = conversationStore.createNewSession(workDir.toString());
            ChatInteractor createdInteractor = new ChatInteractor(
                chatService,
                new DefaultManualToolExecutor(),
                conversationStore,
                created.sessionId());
            interactorRef.set(createdInteractor);
            chatHistory.updateTranscript(createdInteractor.getTranscript());
            refreshSessionsRef[0].run();
            // 新規セッションの作業ディレクトリを表示に反映（JSON が源泉）
            baseDirLabel.setText("作業ディレクトリ: " + interactorRef.get().getWorkingDirectory().toString());
        });

        Button deleteChatButton = new Button("削除");
        deleteChatButton.setOnAction(event -> {
            SessionSummary selected = sessionList.getSelectionModel().getSelectedItem();
            if (selected == null) {
                return;
            }

            Alert confirm = new Alert(Alert.AlertType.CONFIRMATION);
            confirm.setTitle("履歴の削除");
            confirm.setHeaderText("この会話履歴を削除しますか？");
            confirm.setContentText(selected.title());

            if (confirm.showAndWait().orElse(ButtonType.CANCEL) != ButtonType.OK) {
                return;
            }

            conversationStore.deleteSession(selected.sessionId());

            java.util.List<SessionSummary> remainings = conversationStore.listSessions();
            if (remainings.isEmpty()) {
                ConversationSession created = conversationStore.createNewSession(workDir.toString());
                ChatInteractor createdInteractor = new ChatInteractor(
                    chatService,
                    new DefaultManualToolExecutor(),
                    conversationStore,
                    created.sessionId());
                interactorRef.set(createdInteractor);
                chatHistory.updateTranscript(createdInteractor.getTranscript());
                    // セッション作成後の作業ディレクトリ表示更新（JSON が源泉）
                    baseDirLabel.setText("作業ディレクトリ: " + interactorRef.get().getWorkingDirectory().toString());
            } else {
                SessionSummary next = remainings.get(0);
                ChatInteractor selectedInteractor = new ChatInteractor(
                    chatService,
                    new DefaultManualToolExecutor(),
                    conversationStore,
                    next.sessionId());
                interactorRef.set(selectedInteractor);
                chatHistory.updateTranscript(selectedInteractor.getTranscript());
                    // 選択したセッションの作業ディレクトリ表示更新（JSON が源泉）
                    baseDirLabel.setText("作業ディレクトリ: " + interactorRef.get().getWorkingDirectory().toString());
            }
            refreshSessionsRef[0].run();
        });
        deleteChatButton.disableProperty().bind(sessionList.getSelectionModel().selectedItemProperty().isNull());

        sessionList.getSelectionModel().selectedItemProperty().addListener((obs, oldValue, newValue) -> {
            if (newValue == null) {
                return;
            }
            if (newValue.sessionId().equals(interactorRef.get().getCurrentSessionId())) {
                return;
            }
            ChatInteractor selectedInteractor = new ChatInteractor(
                chatService,
                new DefaultManualToolExecutor(),
                conversationStore,
                newValue.sessionId());
            interactorRef.set(selectedInteractor);
            chatHistory.updateTranscript(selectedInteractor.getTranscript());
            // セッション切替時に作業ディレクトリ表示を更新（JSON が源泉）
            baseDirLabel.setText("作業ディレクトリ: " + interactorRef.get().getWorkingDirectory().toString());
        });

        refreshSessionsRef[0].run();

        // 履歴行の右クリックで削除できるコンテキストメニューを追加
        sessionList.setCellFactory(lv -> {
            javafx.scene.control.ListCell<SessionSummary> cell = new javafx.scene.control.ListCell<>() {
                @Override
                protected void updateItem(SessionSummary item, boolean empty) {
                    super.updateItem(item, empty);
                    setText(empty || item == null ? null : item.title());
                }
            };

            javafx.scene.control.MenuItem deleteItem = new javafx.scene.control.MenuItem("削除");
            deleteItem.setOnAction(ev -> {
                SessionSummary item = cell.getItem();
                if (item == null) return;

                Alert confirm = new Alert(Alert.AlertType.CONFIRMATION);
                confirm.setTitle("履歴の削除");
                confirm.setHeaderText("この会話履歴を削除しますか？");
                confirm.setContentText(item.title());

                if (confirm.showAndWait().orElse(ButtonType.CANCEL) != ButtonType.OK) {
                    return;
                }

                conversationStore.deleteSession(item.sessionId());

                java.util.List<SessionSummary> remainings = conversationStore.listSessions();
                if (remainings.isEmpty()) {
                    ConversationSession created = conversationStore.createNewSession(workDir.toString());
                    ChatInteractor createdInteractor = new ChatInteractor(
                        chatService,
                        new DefaultManualToolExecutor(),
                        conversationStore,
                        created.sessionId());
                    interactorRef.set(createdInteractor);
                    chatHistory.updateTranscript(createdInteractor.getTranscript());
                    // セッション作成後の作業ディレクトリ表示更新（JSON が源泉）
                    baseDirLabel.setText("作業ディレクトリ: " + interactorRef.get().getWorkingDirectory().toString());
                } else {
                    SessionSummary next = remainings.get(0);
                    ChatInteractor selectedInteractor = new ChatInteractor(
                        chatService,
                        new DefaultManualToolExecutor(),
                        conversationStore,
                        next.sessionId());
                    interactorRef.set(selectedInteractor);
                    chatHistory.updateTranscript(selectedInteractor.getTranscript());
                    // 選択したセッションの作業ディレクトリ表示更新（JSON が源泉）
                    baseDirLabel.setText("作業ディレクトリ: " + interactorRef.get().getWorkingDirectory().toString());
                }
                refreshSessionsRef[0].run();
            });

            javafx.scene.control.ContextMenu menu = new javafx.scene.control.ContextMenu(deleteItem);
            cell.setContextMenu(menu);
            return cell;
        });

        HBox historyActions = new HBox(8, newChatButton, deleteChatButton);
        VBox historyPane = new VBox(8, new Label("履歴"), historyActions, sessionList);
        historyPane.setPadding(new Insets(8));
        HBox.setHgrow(newChatButton, Priority.ALWAYS);
        HBox.setHgrow(deleteChatButton, Priority.ALWAYS);
        newChatButton.setMaxWidth(Double.MAX_VALUE);
        deleteChatButton.setMaxWidth(Double.MAX_VALUE);
        VBox.setVgrow(sessionList, Priority.ALWAYS);

        // 複数行入力欄（Shift+Enter で改行、Ctrl+Enter で送信）
        TextArea inputField = new TextArea();
        inputField.setPromptText("メッセージを入力... 例: /tool help（Ctrl+Enter で送信）");
        inputField.setWrapText(true);
        inputField.setPrefRowCount(3);
        inputField.setMaxHeight(120);
        HBox.setHgrow(inputField, Priority.ALWAYS);
        // ベースディレクトリ表示と変更ボタン（送信アクションからも更新できるようここで生成）
        baseDirLabel.setText("作業ディレクトリ: " + interactorRef.get().getWorkingDirectory().toString());
        Button changeBaseDirButton = new Button("変更");
        changeBaseDirButton.setOnAction(ev -> {
            DirectoryChooser chooser = new DirectoryChooser();
            chooser.setTitle("作業ディレクトリを選択");
            chooser.setInitialDirectory(new File(baseDirLabel.getText().replaceFirst("^作業ディレクトリ: ", "")));
            File selected = chooser.showDialog(stage);
            if (selected != null) {
                Path newDir = selected.toPath();
                interactorRef.get().updateWorkingDirectory(newDir);
                baseDirLabel.setText("作業ディレクトリ: " + newDir.toString());
            }
        });

        Button sendButton = new Button("送信");
        Runnable sendAction = () -> {
            String userInput = inputField.getText().trim();
            if (userInput.isEmpty()) {
                return;
            }

            ChatInteractor activeInteractor = interactorRef.get();

            inputField.clear();
            inputField.setDisable(true);
            sendButton.setDisable(true);
            sendButton.setText("応答中...");
            newChatButton.setDisable(true);
            // bind中のプロパティは直接setDisableできないためunbindしてから無効化
            deleteChatButton.disableProperty().unbind();
            deleteChatButton.setDisable(true);

            Thread.ofVirtual().start(() -> {
                activeInteractor.startUserMessageStream(
                    userInput,
                    token -> Platform.runLater(() -> chatHistory.appendStreamingToken(token)),
                    () -> Platform.runLater(() -> {
                        // 完了時: ハイライト付き全文再描画
                        if (interactorRef.get() == activeInteractor) {
                            chatHistory.updateTranscript(activeInteractor.getTranscript());
                        } else {
                            chatHistory.updateTranscript(interactorRef.get().getTranscript());
                        }
                        refreshSessionsRef[0].run();
                        // 作業ディレクトリ表示を最新化（JSON が源泉）
                        baseDirLabel.setText("作業ディレクトリ: " + activeInteractor.getWorkingDirectory().toString());
                        inputField.setDisable(false);
                        sendButton.setDisable(false);
                        sendButton.setText("送信");
                        newChatButton.setDisable(false);
                        // bindを再設定して通常動作に戻す
                        deleteChatButton.disableProperty().bind(
                            sessionList.getSelectionModel().selectedItemProperty().isNull());
                        inputField.requestFocus();
                    }),
                    error -> Platform.runLater(() -> {
                        chatHistory.appendStreamingToken("\n\n(エラー) " + error.getMessage());
                        inputField.setDisable(false);
                        sendButton.setDisable(false);
                        sendButton.setText("送信");
                        newChatButton.setDisable(false);
                        deleteChatButton.disableProperty().bind(
                            sessionList.getSelectionModel().selectedItemProperty().isNull());
                        inputField.requestFocus();
                    })
                );
            });
        };

        sendButton.setOnAction(event -> sendAction.run());

        inputField.addEventFilter(KeyEvent.KEY_PRESSED, event -> {
            if (event.getCode() == KeyCode.ENTER && event.isControlDown()) {
                event.consume();
                sendAction.run();
            }
        });

        HBox inputRow = new HBox(8, inputField, sendButton);
        BorderPane chatPane = new BorderPane();
        chatPane.setCenter(chatHistory);
        chatPane.setBottom(inputRow);

        SplitPane splitPane = new SplitPane(historyPane, chatPane);
        splitPane.setDividerPositions(0.24);

        Button toggleHistoryButton = new Button("履歴を閉じる");
        final boolean[] collapsed = {false};
        Runnable applyHistoryPaneState = () -> {
            if (collapsed[0]) {
                splitPane.getItems().setAll(chatPane);
                toggleHistoryButton.setText("履歴を開く");
            } else {
                splitPane.getItems().setAll(historyPane, chatPane);
                splitPane.setDividerPositions(0.24);
                toggleHistoryButton.setText("履歴を閉じる");
            }
        };
        applyHistoryPaneState.run();

        toggleHistoryButton.setOnAction(event -> {
            collapsed[0] = !collapsed[0];
            applyHistoryPaneState.run();
        });

        Button sysPromptButton = new Button("システムプロンプト");
        sysPromptButton.setOnAction(event -> {
            Dialog<String> dialog = new Dialog<>();
            dialog.setTitle("システムプロンプト");
            dialog.setHeaderText("システムプロンプトを編集してください");

            ButtonType saveButtonType = new ButtonType("保存", ButtonBar.ButtonData.OK_DONE);
            dialog.getDialogPane().getButtonTypes().addAll(saveButtonType, ButtonType.CANCEL);

            TextArea sysPromptArea = new TextArea(interactorRef.get().getSystemPrompt());
            sysPromptArea.setWrapText(true);
            sysPromptArea.setPrefRowCount(8);

            // 可変サイズ対応: VBox に入れて垂直方向に拡張されるようにする
            VBox contentBox = new VBox(sysPromptArea);
            contentBox.setPrefSize(600, 360);
            VBox.setVgrow(sysPromptArea, Priority.ALWAYS);

            dialog.getDialogPane().setContent(contentBox);
            dialog.setResizable(true);

            // ダイアログのサイズ変化に合わせて TextArea が追随するようバインド
            dialog.getDialogPane().prefWidthProperty().addListener((obs, oldV, newV) -> {
                sysPromptArea.setPrefWidth(newV.doubleValue() - 20);
            });
            dialog.getDialogPane().prefHeightProperty().addListener((obs, oldV, newV) -> {
                sysPromptArea.setPrefHeight(newV.doubleValue() - 120);
            });

            dialog.setResultConverter(bt -> bt == saveButtonType ? sysPromptArea.getText() : null);
            dialog.showAndWait().ifPresent(text -> interactorRef.get().setSystemPrompt(text));
        });

        HBox topBar = new HBox(8, toggleHistoryButton, sysPromptButton);

        // 全コピーボタン：現在の会話履歴をクリップボードにコピー
        Button copyAllButton = new Button("全コピー");
        copyAllButton.setOnAction(event -> chatHistory.copyToClipboard());
        // 最新ターンコピーボタンは不要になったため、単に全コピーボタンのみ表示
        topBar.getChildren().add(copyAllButton);

        Region spacer = new Region();
        HBox.setHgrow(spacer, Priority.ALWAYS);
        topBar.getChildren().addAll(spacer, baseDirLabel, changeBaseDirButton);

        BorderPane root = new BorderPane();
        root.setPadding(new Insets(12));
        root.setTop(topBar);
        root.setCenter(splitPane);

        Scene scene = new Scene(root, 920, 560);
        stage.setTitle(APP_NAME);
        stage.setScene(scene);
        stage.show();
    }
}
