/*
 * This source file was generated by the Gradle 'init' task
 */
package jp.euks.myagent2.chat;

import jp.euks.myagent2.session.*;
import jp.euks.myagent2.tools.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.file.Path;
import java.util.concurrent.atomic.AtomicReference;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonBar;
import javafx.scene.control.ButtonType;
import javafx.scene.control.Dialog;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.control.SplitPane;
import javafx.scene.control.TextArea;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyEvent;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Region;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.stage.DirectoryChooser;
import javafx.scene.web.WebView;
import javafx.scene.web.WebEngine;
import java.io.File;

/**
 * JavaFX アプリケーションのエントリポイント。
 * シンプルなチャット UI を構築し、`ChatInteractor` を介してメッセージ送受信を行う。
 */
public class App extends Application {
    private static final String APP_NAME = "MyAIAgent2";
    private static final String TOOL_RESULTS_BEGIN_MARKER = "<<TOOL_RESULTS_BEGIN>>";
    private static final String TOOL_RESULTS_END_MARKER = "<<TOOL_RESULTS_END>>";

    /**
     * Java アプリケーションのメインメソッド。JavaFX を起動する。
     *
     * @param args コマンドライン引数
     */
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    /**
     * JavaFX のステージを初期化してチャット UI を配置する。
     *
     * @param stage メインステージ
     */
    public void start(Stage stage) {
        Logger log = LoggerFactory.getLogger(App.class);
        Path workDir = Path.of(System.getProperty("user.dir"));
        ConversationStore conversationStore = new JsonConversationStore(workDir);
        ChatService chatService = ChatServiceFactory.createDefault();
        // 初期作業ディレクトリを設定して UI に表示できるようにしておく
        chatService.setWorkingDirectory(workDir);

        // 起動時は必ず新規セッションから開始する（初期ディレクトリをセッションに保存）
        ConversationSession initial = conversationStore.createNewSession(workDir.toString());
        ChatInteractor initialInteractor = new ChatInteractor(
            chatService,
            new DefaultManualToolExecutor(),
            conversationStore,
            initial.sessionId());
        AtomicReference<ChatInteractor> interactorRef = new AtomicReference<>(initialInteractor);

        ChatDisplayPane chatHistory = new ChatDisplayPane();
        chatHistory.updateTranscript(interactorRef.get().getTranscript());
        WebView webView = new WebView();
        WebEngine webEngine = webView.getEngine();
        updateWebPreview(webEngine, interactorRef.get().getTranscript());

        ListView<SessionSummary> sessionList = new ListView<>();
        sessionList.setPrefWidth(220);

        Runnable[] refreshSessionsRef = new Runnable[1];
        refreshSessionsRef[0] = () -> {
            sessionList.getItems().setAll(conversationStore.listSessions());
            String currentSessionId = interactorRef.get().getCurrentSessionId();
            if (currentSessionId.isBlank()) {
                return;
            }
            for (SessionSummary summary : sessionList.getItems()) {
                if (currentSessionId.equals(summary.sessionId())) {
                    sessionList.getSelectionModel().select(summary);
                    break;
                }
            }
        };

        // 作業ディレクトリ表示ラベルを先に用意しておく（セッション切替時に更新するため）
        Label baseDirLabel = new Label();

        Button newChatButton = new Button("+ 新規");
        newChatButton.setOnAction(event -> {
            ConversationSession created = conversationStore.createNewSession(workDir.toString());
            switchToSession(chatService, conversationStore, interactorRef, chatHistory, webEngine, refreshSessionsRef[0], baseDirLabel, created.sessionId());
        });

        Button deleteChatButton = new Button("削除");
        deleteChatButton.setOnAction(event -> {
            SessionSummary selected = sessionList.getSelectionModel().getSelectedItem();
            if (selected == null) {
                return;
            }

            Alert confirm = new Alert(Alert.AlertType.CONFIRMATION);
            confirm.setTitle("履歴の削除");
            confirm.setHeaderText("この会話履歴を削除しますか？");
            confirm.setContentText(selected.title());

            if (confirm.showAndWait().orElse(ButtonType.CANCEL) != ButtonType.OK) {
                return;
            }

            conversationStore.deleteSession(selected.sessionId());

            java.util.List<SessionSummary> remainings = conversationStore.listSessions();
            if (remainings.isEmpty()) {
                ConversationSession created = conversationStore.createNewSession(workDir.toString());
                switchToSession(chatService, conversationStore, interactorRef, chatHistory, webEngine, refreshSessionsRef[0], baseDirLabel, created.sessionId());
            } else {
                SessionSummary next = remainings.get(0);
                switchToSession(chatService, conversationStore, interactorRef, chatHistory, webEngine, refreshSessionsRef[0], baseDirLabel, next.sessionId());
            }
            refreshSessionsRef[0].run();
        });
        deleteChatButton.disableProperty().bind(sessionList.getSelectionModel().selectedItemProperty().isNull());

        sessionList.getSelectionModel().selectedItemProperty().addListener((obs, oldValue, newValue) -> {
            if (newValue == null) {
                return;
            }
            if (newValue.sessionId().equals(interactorRef.get().getCurrentSessionId())) {
                return;
            }
            switchToSession(chatService, conversationStore, interactorRef, chatHistory, webEngine, refreshSessionsRef[0], baseDirLabel, newValue.sessionId());
        });

        refreshSessionsRef[0].run();

        // 履歴行の右クリックで削除できるコンテキストメニューを追加
        sessionList.setCellFactory(lv -> {
            javafx.scene.control.ListCell<SessionSummary> cell = new javafx.scene.control.ListCell<>() {
                @Override
                protected void updateItem(SessionSummary item, boolean empty) {
                    super.updateItem(item, empty);
                    setText(empty || item == null ? null : item.title());
                }
            };

            javafx.scene.control.MenuItem deleteItem = new javafx.scene.control.MenuItem("削除");
            deleteItem.setOnAction(ev -> {
                SessionSummary item = cell.getItem();
                if (item == null) return;

                Alert confirm = new Alert(Alert.AlertType.CONFIRMATION);
                confirm.setTitle("履歴の削除");
                confirm.setHeaderText("この会話履歴を削除しますか？");
                confirm.setContentText(item.title());

                if (confirm.showAndWait().orElse(ButtonType.CANCEL) != ButtonType.OK) {
                    return;
                }

                conversationStore.deleteSession(item.sessionId());

                java.util.List<SessionSummary> remainings = conversationStore.listSessions();
                if (remainings.isEmpty()) {
                    ConversationSession created = conversationStore.createNewSession(workDir.toString());
                    switchToSession(chatService, conversationStore, interactorRef, chatHistory, webEngine, refreshSessionsRef[0], baseDirLabel, created.sessionId());
                } else {
                    SessionSummary next = remainings.get(0);
                    switchToSession(chatService, conversationStore, interactorRef, chatHistory, webEngine, refreshSessionsRef[0], baseDirLabel, next.sessionId());
                }
                refreshSessionsRef[0].run();
            });

            javafx.scene.control.ContextMenu menu = new javafx.scene.control.ContextMenu(deleteItem);
            cell.setContextMenu(menu);
            return cell;
        });

        HBox historyActions = new HBox(8, newChatButton, deleteChatButton);
        VBox historyPane = new VBox(8, new Label("履歴"), historyActions, sessionList);
        historyPane.setPadding(new Insets(8));
        HBox.setHgrow(newChatButton, Priority.ALWAYS);
        HBox.setHgrow(deleteChatButton, Priority.ALWAYS);
        newChatButton.setMaxWidth(Double.MAX_VALUE);
        deleteChatButton.setMaxWidth(Double.MAX_VALUE);
        VBox.setVgrow(sessionList, Priority.ALWAYS);

        // 複数行入力欄（Shift+Enter で改行、Ctrl+Enter で送信）
        TextArea inputField = new TextArea();
        inputField.setPromptText("メッセージを入力... 例: /tool help（Ctrl+Enter で送信）");
        inputField.setWrapText(true);
        inputField.setPrefRowCount(3);
        inputField.setMaxHeight(120);
        HBox.setHgrow(inputField, Priority.ALWAYS);
        // ベースディレクトリ表示と変更ボタン（送信アクションからも更新できるようここで生成）
        baseDirLabel.setText("作業ディレクトリ: " + interactorRef.get().getWorkingDirectory().toString());
        Button changeBaseDirButton = new Button("変更");
        changeBaseDirButton.setOnAction(ev -> {
            DirectoryChooser chooser = new DirectoryChooser();
            chooser.setTitle("作業ディレクトリを選択");
            chooser.setInitialDirectory(new File(baseDirLabel.getText().replaceFirst("^作業ディレクトリ: ", "")));
            File selected = chooser.showDialog(stage);
            if (selected != null) {
                Path newDir = selected.toPath();
                interactorRef.get().updateWorkingDirectory(newDir);
                baseDirLabel.setText("作業ディレクトリ: " + newDir.toString());
            }
        });

        Button sendButton = new Button("送信");
        Runnable sendAction = () -> {
            String userInput = inputField.getText().trim();
            if (userInput.isEmpty()) {
                return;
            }

            ChatInteractor activeInteractor = interactorRef.get();

            inputField.clear();
            inputField.setDisable(true);
            sendButton.setDisable(true);
            sendButton.setText("応答中...");
            newChatButton.setDisable(true);
            // bind中のプロパティは直接setDisableできないためunbindしてから無効化
            deleteChatButton.disableProperty().unbind();
            deleteChatButton.setDisable(true);

            Thread.ofVirtual().start(() -> {
                activeInteractor.startUserMessageStream(
                    userInput,
                    token -> Platform.runLater(() -> chatHistory.appendStreamingToken(token)),
                    () -> Platform.runLater(() -> {
                        // 完了時: ハイライト付き全文再描画
                        if (interactorRef.get() == activeInteractor) {
                            chatHistory.updateTranscript(activeInteractor.getTranscript());
                            updateWebPreview(webEngine, activeInteractor.getTranscript());
                        } else {
                            chatHistory.updateTranscript(interactorRef.get().getTranscript());
                            updateWebPreview(webEngine, interactorRef.get().getTranscript());
                        }
                        refreshSessionsRef[0].run();
                        // 作業ディレクトリ表示を最新化（JSON が源泉）
                        baseDirLabel.setText("作業ディレクトリ: " + activeInteractor.getWorkingDirectory().toString());
                        inputField.setDisable(false);
                        sendButton.setDisable(false);
                        sendButton.setText("送信");
                        newChatButton.setDisable(false);
                        // bindを再設定して通常動作に戻す
                        deleteChatButton.disableProperty().bind(
                            sessionList.getSelectionModel().selectedItemProperty().isNull());
                        inputField.requestFocus();
                    }),
                    error -> Platform.runLater(() -> {
                        chatHistory.appendStreamingToken("\n\n(エラー) " + error.getMessage());
                        inputField.setDisable(false);
                        sendButton.setDisable(false);
                        sendButton.setText("送信");
                        newChatButton.setDisable(false);
                        deleteChatButton.disableProperty().bind(
                            sessionList.getSelectionModel().selectedItemProperty().isNull());
                        inputField.requestFocus();
                    })
                );
            });
        };

        sendButton.setOnAction(event -> sendAction.run());

        inputField.addEventFilter(KeyEvent.KEY_PRESSED, event -> {
            if (event.getCode() == KeyCode.ENTER && event.isControlDown()) {
                event.consume();
                sendAction.run();
            }
        });

        HBox inputRow = new HBox(8, inputField, sendButton);
        BorderPane chatPane = new BorderPane();
        chatPane.setCenter(webView);
        chatPane.setBottom(inputRow);

        SplitPane splitPane = new SplitPane(historyPane, chatPane);
        splitPane.setDividerPositions(0.24);

        Button toggleHistoryButton = new Button("履歴を閉じる");
        final boolean[] collapsed = {false};
        Runnable applyHistoryPaneState = () -> {
            if (collapsed[0]) {
                splitPane.getItems().setAll(chatPane);
                toggleHistoryButton.setText("履歴を開く");
            } else {
                splitPane.getItems().setAll(historyPane, chatPane);
                splitPane.setDividerPositions(0.24);
                toggleHistoryButton.setText("履歴を閉じる");
            }
        };
        applyHistoryPaneState.run();

        toggleHistoryButton.setOnAction(event -> {
            collapsed[0] = !collapsed[0];
            applyHistoryPaneState.run();
        });

        Button sysPromptButton = new Button("システムプロンプト");
        sysPromptButton.setOnAction(event -> {
            Dialog<String> dialog = new Dialog<>();
            dialog.setTitle("システムプロンプト");
            dialog.setHeaderText("システムプロンプトを編集してください");

            ButtonType saveButtonType = new ButtonType("保存", ButtonBar.ButtonData.OK_DONE);
            dialog.getDialogPane().getButtonTypes().addAll(saveButtonType, ButtonType.CANCEL);

            TextArea sysPromptArea = new TextArea(interactorRef.get().getSystemPrompt());
            sysPromptArea.setWrapText(true);
            sysPromptArea.setPrefRowCount(8);

            // 可変サイズ対応: VBox に入れて垂直方向に拡張されるようにする
            VBox contentBox = new VBox(sysPromptArea);
            contentBox.setPrefSize(600, 360);
            VBox.setVgrow(sysPromptArea, Priority.ALWAYS);

            dialog.getDialogPane().setContent(contentBox);
            dialog.setResizable(true);

            // ダイアログのサイズ変化に合わせて TextArea が追随するようバインド
            dialog.getDialogPane().prefWidthProperty().addListener((obs, oldV, newV) -> {
                sysPromptArea.setPrefWidth(newV.doubleValue() - 20);
            });
            dialog.getDialogPane().prefHeightProperty().addListener((obs, oldV, newV) -> {
                sysPromptArea.setPrefHeight(newV.doubleValue() - 120);
            });

            dialog.setResultConverter(bt -> bt == saveButtonType ? sysPromptArea.getText() : null);
            dialog.showAndWait().ifPresent(text -> interactorRef.get().setSystemPrompt(text));
        });

        HBox topBar = new HBox(8, toggleHistoryButton, sysPromptButton);

        // 全コピーボタン：現在の会話履歴をクリップボードにコピー
        Button copyAllButton = new Button("全コピー");
        copyAllButton.setOnAction(event -> chatHistory.copyToClipboard());
        // 最新ターンコピーボタンは不要になったため、単に全コピーボタンのみ表示
        topBar.getChildren().add(copyAllButton);

        Region spacer = new Region();
        HBox.setHgrow(spacer, Priority.ALWAYS);
        topBar.getChildren().addAll(spacer, baseDirLabel, changeBaseDirButton);

        BorderPane root = new BorderPane();
        root.setPadding(new Insets(12));
        root.setTop(topBar);
        root.setCenter(splitPane);

        Scene scene = new Scene(root, 920, 560);
        stage.setTitle(APP_NAME);
        stage.setScene(scene);
        stage.show();
    }

    private void switchToSession(
        ChatService chatService,
        ConversationStore conversationStore,
        AtomicReference<ChatInteractor> interactorRef,
        ChatDisplayPane chatHistory,
        WebEngine webEngine,
        Runnable refreshSessions,
        Label baseDirLabel,
        String sessionId) {

        if (sessionId == null || sessionId.isBlank()) {
            return;
        }

        // LLM 側のメモリをクリアしてから新しいセッションを読み込む
        chatService.clearMemory();

        ChatInteractor selectedInteractor = new ChatInteractor(
            chatService,
            new DefaultManualToolExecutor(),
            conversationStore,
            sessionId);

        interactorRef.set(selectedInteractor);
        chatHistory.updateTranscript(selectedInteractor.getTranscript());
        updateWebPreview(webEngine, selectedInteractor.getTranscript());
        baseDirLabel.setText("作業ディレクトリ: " + interactorRef.get().getWorkingDirectory().toString());

        if (refreshSessions != null) {
            try {
                refreshSessions.run();
            } catch (Exception ignored) {
            }
        }
    }

    private static void updateWebPreview(WebEngine webEngine, String transcript) {
        String sanitized = transcript == null ? "" : transcript;
        sanitized = sanitized.replaceAll("[\uFEFF\u200B\u200C\u200D]", "");
        sanitized = sanitized.replaceAll("[\\p{Cc}&&[^\\r\\n\\t]]", "");

        String body = sanitized.isBlank()
            ? "<p class='empty'>（会話履歴はまだありません）</p>"
            : renderTranscriptHtml(sanitized);

        String html = """
            <!DOCTYPE html>
            <html lang='ja'>
            <head>
              <meta charset='UTF-8'>
              <style>
                * { -webkit-font-smoothing: antialiased; text-rendering: optimizeLegibility; }
                body {
                  font-family: 'Yu Gothic UI', 'Yu Gothic', 'Meiryo', 'Noto Sans JP', 'Consolas', monospace, sans-serif;
                  margin: 16px; background: #fafafa; color: #1f2937; font-size: 13px;
                }
                h2 { margin: 0 0 12px 0; font-size: 18px; }
                .panel { background: #fff; border: 1px solid #e5e7eb; border-radius: 10px; padding: 12px; }
                .msg-row { display: flex; align-items: baseline; gap: 6px; margin: 3px 0; }
                .label-you { color: #0066cc; font-weight: 600; white-space: nowrap; }
                .label-assistant { color: #008000; font-weight: 600; white-space: nowrap; }
                .md-content { flex: 1; line-height: 1.6; }
                .md-content > *:first-child { margin-top: 0; }
                .md-content > *:last-child { margin-bottom: 0; }
                .md-content p { margin: 0 0 4px 0; }
                .md-content pre { background: #f3f4f6; border-radius: 4px; padding: 8px; overflow-x: auto; margin: 4px 0; }
                .md-content code { background: #f3f4f6; border-radius: 3px; padding: 1px 4px; font-family: 'Consolas', monospace; font-size: 12px; }
                .md-content pre code { background: none; padding: 0; }
                .md-content ul, .md-content ol { margin: 4px 0; padding-left: 20px; }
                .md-content h1,.md-content h2,.md-content h3 { margin: 8px 0 4px 0; font-size: 14px; }
                .plain-content { flex: 1; white-space: pre-wrap; word-break: break-word; line-height: 1.5; }
                .empty { color: #6b7280; }
                details.tool { margin: 8px 0; border: 1px solid #d1d5db; border-radius: 8px; background: #fcfcfd; }
                details.tool > summary { cursor: pointer; padding: 8px 10px; color: #ff6600; font-weight: 700; user-select: none; }
                details.tool > pre {
                  margin: 0; padding: 10px; border-top: 1px solid #e5e7eb;
                  white-space: pre-wrap; word-break: break-word; line-height: 1.5; font-size: 13px; background: #fff;
                  font-family: 'Yu Gothic UI', 'Yu Gothic', 'Meiryo', 'Consolas', monospace, sans-serif;
                }
              </style>
            </head>
            <body>
              <h2>会話プレビュー</h2>
              <div class='panel'>
            """ + body + """
              </div>
              <script src='https://cdn.jsdelivr.net/npm/marked/marked.min.js'></script>
              <script>
                if (typeof marked !== 'undefined') {
                  marked.setOptions({ breaks: true });
                  document.querySelectorAll('.md-content[data-md]').forEach(function(el) {
                    el.innerHTML = marked.parse(el.getAttribute('data-md'));
                  });
                }
              </script>
            </body>
            </html>
            """;
        webEngine.loadContent(html, "text/html");
    }

    private static String renderTranscriptHtml(String transcript) {
        String[] lines = transcript.split("\n", -1);
        StringBuilder html = new StringBuilder();

        String currentRole = "NONE"; // YOU, ASSISTANT, NONE
        StringBuilder currentContent = new StringBuilder();
        boolean inToolBlock = false;
        StringBuilder toolContent = new StringBuilder();
        String toolName = "tool";

        for (String line : lines) {
            if (isToolBlockBeginLine(line)) {
                if (!"NONE".equals(currentRole) && currentContent.length() > 0) {
                    flushBlock(html, currentRole, currentContent.toString());
                    currentContent.setLength(0);
                    currentRole = "NONE";
                }
                inToolBlock = true;
                toolName = "tool";
                toolContent.setLength(0);
                continue;
            }
            if (isToolBlockEndLine(line)) {
                appendToolBlockHtml(html, toolName, toolContent.toString());
                inToolBlock = false;
                toolContent.setLength(0);
                toolName = "tool";
                continue;
            }
            if (inToolBlock) {
                String normalized = stripChatLabelPrefix(line);
                if (toolContent.length() > 0) {
                    toolContent.append("\n");
                }
                toolContent.append(normalized);
                if ("tool".equals(toolName) && isToolResultLine(normalized)) {
                    toolName = extractToolName(normalized);
                }
                continue;
            }

            Matcher youMatcher = Pattern.compile("^You:\\s+(.*)$").matcher(line);
            Matcher assistantMatcher = Pattern.compile("^Assistant:\\s+(.*)$").matcher(line);

            if (youMatcher.matches()) {
                if (!"NONE".equals(currentRole) && currentContent.length() > 0) {
                    flushBlock(html, currentRole, currentContent.toString());
                }
                currentRole = "YOU";
                currentContent = new StringBuilder(youMatcher.group(1));
            } else if (assistantMatcher.matches()) {
                if (!"NONE".equals(currentRole) && currentContent.length() > 0) {
                    flushBlock(html, currentRole, currentContent.toString());
                }
                currentRole = "ASSISTANT";
                currentContent = new StringBuilder(assistantMatcher.group(1));
            } else {
                if (!"NONE".equals(currentRole)) {
                    currentContent.append("\n").append(line);
                } else if (!line.isBlank()) {
                    html.append("<div class='plain-content'>").append(escapeHtml(line)).append("</div>");
                }
            }
        }

        if (inToolBlock && toolContent.length() > 0) {
            appendToolBlockHtml(html, toolName, toolContent.toString());
        } else if (!"NONE".equals(currentRole) && currentContent.length() > 0) {
            flushBlock(html, currentRole, currentContent.toString());
        }
        return html.toString();
    }

    private static void flushBlock(StringBuilder html, String role, String content) {
        if ("YOU".equals(role)) {
            html.append("<div class='msg-row'>")
                .append("<span class='label-you'>You:</span>")
                .append("<div class='plain-content'>")
                .append(escapeHtml(content))
                .append("</div></div>\n");
        } else if ("ASSISTANT".equals(role)) {
            html.append("<div class='msg-row'>")
                .append("<span class='label-assistant'>Assistant:</span>")
                .append("<div class='md-content' data-md='")
                .append(escapeHtmlAttr(content))
                .append("'></div></div>\n");
        }
    }

    private static String escapeHtmlAttr(String text) {
        if (text == null) {
            return "";
        }
        return text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&#39;");
    }

    private static void appendToolBlockHtml(StringBuilder html, String toolName, String content) {
        String visibleName = (toolName == null || toolName.isBlank()) ? "tool" : toolName;
        html.append("<details class='tool'><summary>")
            .append(escapeHtml(visibleName))
            .append(" の結果</summary><pre>")
            .append(escapeHtml(content))
            .append("</pre></details>");
    }

    private static boolean isToolBlockBeginLine(String line) {
        return normalizeToolLine(line).equals(TOOL_RESULTS_BEGIN_MARKER);
    }

    private static boolean isToolBlockEndLine(String line) {
        return normalizeToolLine(line).equals(TOOL_RESULTS_END_MARKER);
    }

    private static boolean isToolResultLine(String line) {
        String normalized = normalizeToolLine(line);
        return normalized.matches("^\\(tool:\\w+\\).*")
            || normalized.matches("^[^\\p{L}\\p{N}\\s(]\\s*\\w+:.*");
    }

    private static String extractToolName(String line) {
        String normalized = normalizeToolLine(line);

        Matcher m1 = Pattern.compile("^\\(tool:(\\w+)\\)").matcher(normalized);
        if (m1.find()) {
            return m1.group(1);
        }
        Matcher m2 = Pattern.compile("^[^\\p{L}\\p{N}\\s(]\\s*(\\w+):").matcher(normalized);
        if (m2.find()) {
            return m2.group(1);
        }
        return "tool";
    }

    private static String normalizeToolLine(String line) {
        if (line == null) {
            return "";
        }
        return line.replaceFirst("^Assistant:\\s+", "");
    }

    private static String stripChatLabelPrefix(String line) {
        if (line == null) {
            return "";
        }
        return line.replaceFirst("^(You|Assistant):\\s+", "");
    }

    private static String escapeHtml(String text) {
        if (text == null) {
            return "";
        }
        return text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;");
    }
}
