package jp.euks.myagent2.chat;

import java.util.Objects;
/*
 * This source file was generated by the Gradle 'init' task
 */
import jp.euks.myagent2.session.*;
import jp.euks.myagent2.tools.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.nio.file.Path;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.atomic.AtomicReference;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.io.InputStream;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonBar;
import javafx.scene.control.ButtonType;
import javafx.scene.control.Dialog;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.control.SplitPane;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextInputDialog;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyEvent;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Region;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.scene.input.Clipboard;
import javafx.scene.input.ClipboardContent;
import javafx.scene.input.KeyCodeCombination;
import javafx.scene.input.KeyCombination;
import javafx.stage.Stage;
import javafx.stage.DirectoryChooser;
import javafx.scene.web.WebView;
import javafx.scene.web.WebEngine;
import java.io.File;

/**
 * JavaFX アプリケーションのエントリポイント。
 * シンプルなチャット UI を構築し、`ChatInteractor` を介してメッセージ送受信を行う。
 */
public class App extends Application {
    private static final String APP_NAME = "MyAIAgent2";
    private static final String TOOL_RESULTS_BEGIN_MARKER = "<<TOOL_RESULTS_BEGIN>>";
    private static final String TOOL_RESULTS_END_MARKER = "<<TOOL_RESULTS_END>>";
    private static final Pattern YOU_LINE_PATTERN = Pattern.compile("^You:\\s+(.*)$");
    private static final Pattern ASSISTANT_LINE_PATTERN = Pattern.compile("^Assistant:\\s+(.*)$");
    private static final Pattern TOOL_NAME_PATTERN_1 = Pattern.compile("^\\(tool:(\\w+)\\)");
    private static final Pattern TOOL_NAME_PATTERN_2 = Pattern.compile("^[^\\p{L}\\p{N}\\s(]\\s*(\\w+):");
    private static final String MARKED_JS_INLINE = loadMarkedJsInline();

    /**
     * Java アプリケーションのメインメソッド。JavaFX を起動する。
     *
     * @param args コマンドライン引数
     */
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    /**
     * JavaFX のステージを初期化してチャット UI を配置する。
     *
     * @param stage メインステージ
     */
    public void start(Stage stage) {
        // 作業ディレクトリを取得して会話ストアを初期化
        Path workDir = Path.of(System.getProperty("user.dir"));
        ConversationStore conversationStore = new JsonConversationStore(workDir);

        // SessionRuntimeManager を作成してセッション単位のインスタンス化を管理
        SessionRuntimeManager runtimeManager = new SessionRuntimeManager(5, conversationStore, workDir);

        // 起動時はセッションなしで開始
        AtomicReference<ChatInteractor> interactorRef = new AtomicReference<>(null);

        // UI コンポーネントの構築

        // 会話履歴のプレビュー表示用 WebView を構築
        WebView webView = new WebView();
        WebEngine webEngine = webView.getEngine();
        if (interactorRef.get() != null) {
            updateWebPreview(webEngine, interactorRef.get().getTranscript(), null);
        }

        // セッションリストを構築
        ListView<SessionSummary> sessionList = new ListView<>();
        sessionList.setPrefWidth(220);

        // セッションリストを最新化する Runnable を生成。セッション切替やメッセージ送受信の完了後に呼び出して UI を最新化するために保持しておく。
        Runnable[] refreshSessionsRef = new Runnable[1];
        refreshSessionsRef[0] = createRefreshSessionsRunnable(sessionList, conversationStore, interactorRef);

        // 作業ディレクトリ表示ラベルを先に用意しておく（セッション切替時に更新するため）
        Label baseDirLabel = new Label();
        if (interactorRef.get() != null) {
            baseDirLabel.setText("作業ディレクトリ: " + interactorRef.get().getWorkingDirectory().toString());
        } else {
            baseDirLabel.setText("作業ディレクトリ: " + workDir.toString());
        }

        Button newChatButton = new Button("+ 新規");
        newChatButton.setOnAction(event -> {
            String selectedProvider = showProviderSelectionDialog();
            if (selectedProvider != null) {
                ConversationSession created = conversationStore.createNewSession(workDir.toString());
                created.setProvider(selectedProvider);
                conversationStore.save(created);
                switchToSession(runtimeManager, interactorRef, webEngine, refreshSessionsRef[0], baseDirLabel,
                        created.sessionId(), conversationStore);
            }
        });

        Button deleteChatButton = new Button("削除");
        // 共通削除処理を呼び出す
        deleteChatButton.setOnAction(event -> {
            deleteSessionAndSwitch(sessionList.getSelectionModel().getSelectedItem(), conversationStore, interactorRef,
                    webEngine, refreshSessionsRef[0], baseDirLabel, workDir, runtimeManager);
        });
        deleteChatButton.disableProperty().bind(sessionList.getSelectionModel().selectedItemProperty().isNull());

        // セッションリストの選択変更でセッション切替処理を呼び出す
        sessionList.getSelectionModel().selectedItemProperty().addListener((obs, oldValue, newValue) -> {
            if (Objects.isNull(newValue)) {
                return;
            }
            ChatInteractor current = interactorRef.get();
            if (current != null && newValue.sessionId().equals(current.getCurrentSessionId())) {
                return;
            }
            switchToSession(runtimeManager, interactorRef, webEngine, refreshSessionsRef[0], baseDirLabel,
                    newValue.sessionId(), conversationStore);
        });

        refreshSessionsRef[0].run();
        configureSessionListCellFactory(sessionList, conversationStore, interactorRef, webEngine, refreshSessionsRef,
                baseDirLabel, workDir, runtimeManager);

        HBox historyActions = new HBox(8, newChatButton, deleteChatButton);
        VBox historyPane = new VBox(8, new Label("履歴"), historyActions, sessionList);
        historyPane.setPadding(new Insets(8));
        HBox.setHgrow(newChatButton, Priority.ALWAYS);
        HBox.setHgrow(deleteChatButton, Priority.ALWAYS);
        newChatButton.setMaxWidth(Double.MAX_VALUE);
        deleteChatButton.setMaxWidth(Double.MAX_VALUE);
        VBox.setVgrow(sessionList, Priority.ALWAYS);

        // 複数行入力欄（Shift+Enter で改行、Ctrl+Enter で送信）
        TextArea inputField = new TextArea();
        inputField.setPromptText("メッセージを入力... 例: /tool help（Ctrl+Enter で送信）");
        inputField.setWrapText(true);
        inputField.setPrefRowCount(3);
        inputField.setMaxHeight(120);
        HBox.setHgrow(inputField, Priority.ALWAYS);

        // ベースディレクトリ表示と変更ボタン（送信アクションからも更新できるようここで生成）
        Label progressLabel = new Label();
        progressLabel.setStyle("-fx-text-fill: #FF6600;");
        progressLabel.setVisible(false);
        progressLabel.setManaged(false);
        Button changeBaseDirButton = new Button("変更");
        changeBaseDirButton.setOnAction(ev -> {
            DirectoryChooser chooser = new DirectoryChooser();
            chooser.setTitle("作業ディレクトリを選択");
            chooser.setInitialDirectory(new File(baseDirLabel.getText().replaceFirst("^作業ディレクトリ: ", "")));
            File selected = chooser.showDialog(stage);
            if (selected != null) {
                Path newDir = selected.toPath();
                interactorRef.get().updateWorkingDirectory(newDir);
                baseDirLabel.setText("作業ディレクトリ: " + newDir.toString());
            }
        });

        Button sendButton = new Button("送信");
        Button cancelButton = new Button("キャンセル");
        
        // ★★★ tokenInfoLabel を先に定義（sendAction から参照するため）
        Label tokenInfoLabel = new Label();
        tokenInfoLabel.setId("token-info-label");
        tokenInfoLabel.setPadding(new Insets(0, 10, 0, 5));
        tokenInfoLabel.setStyle("-fx-font-size: 12; -fx-text-fill: #666;");
        
        cancelButton.setDisable(true);
        cancelButton.setOnAction(ev -> {
            ChatInteractor active = interactorRef.get();
            if (active != null) {
                active.cancelCurrentRequest();
                progressLabel.setText("[進捗] キャンセル要求を送信しました");
            }
            cancelButton.setDisable(true);
        });

        // 送信アクションを Runnable として切り出す。これを送信ボタンのアクションと Ctrl+Enter の両方から呼び出す。
        Runnable sendAction = () -> {
            String userInput = inputField.getText().trim();
            if (userInput.isEmpty()) {
                return;
            }

            ChatInteractor activeInteractor = interactorRef.get();
            if (activeInteractor == null) {
                return; // セッション未選択の場合は何もしない
            }

            inputField.clear();
            setSendingUiState(inputField, sendButton, cancelButton, progressLabel, newChatButton, deleteChatButton);

            Thread.ofVirtual().start(() -> {
                activeInteractor.startUserMessageStream(
                        userInput,
                        token -> {
                        },
                        progressText -> Platform.runLater(() -> {
                            progressLabel.setText("[進捗] " + progressText);
                        }),
                        () -> Platform.runLater(() -> {
                            // 完了時: WebViewを再描画
                            if (interactorRef.get() == activeInteractor) {
                                String sessionId = activeInteractor.getCurrentSessionId();
                                ConversationSession sess = conversationStore.loadByIdOrCreate(sessionId);
                                updateWebPreview(webEngine, activeInteractor.getTranscript(), sess.provider());
                            } else {
                                ChatInteractor current = interactorRef.get();
                                if (current != null) {
                                    String sessionId = current.getCurrentSessionId();
                                    ConversationSession sess = conversationStore.loadByIdOrCreate(sessionId);
                                    updateWebPreview(webEngine, current.getTranscript(), sess.provider());
                                }
                            }
                            refreshSessionsRef[0].run();
                            // 作業ディレクトリ表示を最新化（JSON が源泉）
                            baseDirLabel.setText("作業ディレクトリ: " + activeInteractor.getWorkingDirectory().toString());
                            
                            // ★★★ トークン情報を別 UI に表示（今回 + セッション累積）
                            TokenInfo tokenInfo = activeInteractor.getLastTokenInfo();
                            long sessIn = activeInteractor.getSessionTotalInputTokens();
                            long sessOut = activeInteractor.getSessionTotalOutputTokens();
                            if (tokenInfo != null) {
                                String current = String.format("今回: input=%,d output=%,d (計%,d)",
                                        tokenInfo.inputTokens(), tokenInfo.outputTokens(),
                                        tokenInfo.inputTokens() + tokenInfo.outputTokens());
                                String cumul = String.format("累積: input=%,d output=%,d (計%,d)",
                                        sessIn, sessOut, sessIn + sessOut);
                                tokenInfoLabel.setText("●トークン: " + current + "  /  " + cumul);
                            } else if (sessIn + sessOut > 0) {
                                String cumul = String.format("累積: input=%,d output=%,d (計%,d)",
                                        sessIn, sessOut, sessIn + sessOut);
                                tokenInfoLabel.setText("●トークン: " + cumul);
                            } else {
                                tokenInfoLabel.setText("●トークン: 取得不可");
                            }
                            
                            completeMessageHandling(inputField, sendButton, cancelButton, progressLabel, newChatButton,
                                    deleteChatButton, sessionList, null);
                        }),
                        error -> Platform.runLater(() -> {
                            Alert alert = new Alert(Alert.AlertType.ERROR);
                            alert.setTitle("エラー");
                            alert.setHeaderText("応答中にエラーが発生しました");
                            alert.setContentText(error.getMessage());
                            alert.showAndWait();
                            completeMessageHandling(inputField, sendButton, cancelButton, progressLabel, newChatButton,
                                    deleteChatButton, sessionList, null);
                        }));
            });
        };

        sendButton.setOnAction(event -> sendAction.run());
        inputField.addEventFilter(KeyEvent.KEY_PRESSED, event -> {
            if (event.getCode() == KeyCode.ENTER && event.isControlDown()) {
                event.consume();
                sendAction.run();
            }
        });

        HBox inputRow = new HBox(8, inputField, sendButton, cancelButton);
        HBox.setHgrow(inputField, Priority.ALWAYS);
        VBox bottomBox = new VBox(4, progressLabel, tokenInfoLabel, inputRow);
        BorderPane chatPane = new BorderPane();
        chatPane.setCenter(webView);
        chatPane.setBottom(bottomBox);

        SplitPane splitPane = new SplitPane(historyPane, chatPane);
        splitPane.setDividerPositions(0.24);

        Button toggleHistoryButton = new Button("履歴を閉じる");
        final boolean[] collapsed = { false };
        Runnable applyHistoryPaneState = () -> {
            if (collapsed[0]) {
                splitPane.getItems().setAll(chatPane);
                toggleHistoryButton.setText("履歴を開く");
            } else {
                splitPane.getItems().setAll(historyPane, chatPane);
                splitPane.setDividerPositions(0.24);
                toggleHistoryButton.setText("履歴を閉じる");
            }
        };
        applyHistoryPaneState.run();

        toggleHistoryButton.setOnAction(event -> {
            collapsed[0] = !collapsed[0];
            applyHistoryPaneState.run();
        });

        Button sysPromptButton = new Button("システムプロンプト");
        sysPromptButton.setOnAction(event -> {
            ChatInteractor activeInteractor = interactorRef.get();
            if (activeInteractor == null) {
                return;
            }

            Dialog<String> dialog = new Dialog<>();
            dialog.setTitle("システムプロンプト");
            dialog.setHeaderText("システムプロンプトを編集してください");

            ButtonType saveButtonType = new ButtonType("保存", ButtonBar.ButtonData.OK_DONE);
            dialog.getDialogPane().getButtonTypes().addAll(saveButtonType, ButtonType.CANCEL);

            TextArea sysPromptArea = new TextArea(activeInteractor.getSystemPrompt());
            sysPromptArea.setWrapText(true);
            sysPromptArea.setPrefRowCount(8);

            // 可変サイズ対応: VBox に入れて垂直方向に拡張されるようにする
            VBox contentBox = new VBox(sysPromptArea);
            contentBox.setPrefSize(600, 360);
            VBox.setVgrow(sysPromptArea, Priority.ALWAYS);

            dialog.getDialogPane().setContent(contentBox);
            dialog.setResizable(true);

            // ダイアログのサイズ変化に合わせて TextArea が追随するようバインド
            dialog.getDialogPane().prefWidthProperty().addListener((obs, oldV, newV) -> {
                sysPromptArea.setPrefWidth(newV.doubleValue() - 20);
            });
            dialog.getDialogPane().prefHeightProperty().addListener((obs, oldV, newV) -> {
                sysPromptArea.setPrefHeight(newV.doubleValue() - 120);
            });

            dialog.setResultConverter(bt -> bt == saveButtonType ? sysPromptArea.getText() : null);
            dialog.showAndWait().ifPresent(text -> {
                ChatInteractor interactor = interactorRef.get();
                if (interactor != null) {
                    interactor.setSystemPrompt(text);
                }
            });
        });

        Button clearButton = new Button("クリア");
        clearButton.setOnAction(event -> {
            Alert confirm = new Alert(Alert.AlertType.CONFIRMATION);
            confirm.setTitle("会話履歴をクリア");
            confirm.setHeaderText("会話履歴を削除してもよろしいですか？");
            confirm.setContentText("この操作は取り消せません。");

            if (confirm.showAndWait().orElse(ButtonType.CANCEL) == ButtonType.OK) {
                inputField.setText("/clear");
                sendAction.run();
            }
        });

        HBox topBar = new HBox(8, toggleHistoryButton, sysPromptButton, clearButton);

        // 全コピーボタン：現在の会話履歴をクリップボードにコピー
        Button copyAllButton = new Button("全コピー");
        copyAllButton.setOnAction(event -> {
            ChatInteractor interactor = interactorRef.get();
            if (interactor != null) {
                ClipboardContent content = new ClipboardContent();
                content.putString(interactor.getTranscript());
                Clipboard.getSystemClipboard().setContent(content);
            }
        });
        // 最新ターンコピーボタンは不要になったため、単に全コピーボタンのみ表示
        topBar.getChildren().add(copyAllButton);

        Region spacer = new Region();
        HBox.setHgrow(spacer, Priority.ALWAYS);
        topBar.getChildren().addAll(spacer, baseDirLabel, changeBaseDirButton);

        BorderPane root = new BorderPane();
        root.setPadding(new Insets(12));
        root.setTop(topBar);
        root.setCenter(splitPane);

        Scene scene = new Scene(root, 920, 560);
        scene.getAccelerators().put(
                new KeyCodeCombination(KeyCode.D, KeyCombination.ALT_DOWN),
                deleteChatButton::fire);
        stage.setTitle(APP_NAME);
        stage.setScene(scene);
        stage.show();

        // 起動後、セッションリストを表示して最新セッションを自動選択
        Platform.runLater(() -> {
            refreshSessionsRef[0].run();
            var sessions = conversationStore.listSessions();
            if (!sessions.isEmpty()) {
                // 最新のセッション（リストの最初のもの）を選択
                SessionSummary latestSession = sessions.get(0);
                sessionList.getSelectionModel().select(latestSession);
            }
        });
    }

    /**
     * セッションリストを最新化する Runnable を生成するユーティリティ。
     * 
     * @param sessionList       セッションリストの ListView
     * @param conversationStore 会話ストア
     * @param interactorRef     現在の ChatInteractor を保持する AtomicReference
     * @return セッションリストを最新化する Runnable
     */
    private Runnable createRefreshSessionsRunnable(
            ListView<SessionSummary> sessionList,
            ConversationStore conversationStore,
            AtomicReference<ChatInteractor> interactorRef) {
        return () -> {
            sessionList.getItems().setAll(conversationStore.listSessions());
            ChatInteractor interactor = interactorRef.get();
            if (interactor == null) {
                return; // セッション未選択の場合は選択を更新しない
            }
            String currentSessionId = interactor.getCurrentSessionId();
            if (currentSessionId.isBlank()) {
                return;
            }
            for (SessionSummary summary : sessionList.getItems()) {
                if (currentSessionId.equals(summary.sessionId())) {
                    sessionList.getSelectionModel().select(summary);
                    break;
                }
            }
        };
    }

    /**
     * セッションリストのセルファクトリーを構成するユーティリティ。右クリックで削除できるコンテキストメニューを追加する。
     * 
     * @param sessionList        セッションリストの ListView
     * @param conversationStore  会話ストア
     * @param interactorRef      現在の ChatInteractor を保持する AtomicReference
     * @param webEngine          WebView の WebEngine（セッション切替後のプレビュー更新に使用）
     * @param refreshSessionsRef セッションリストを最新化する
     * @param baseDirLabel       作業ディレクトリ表示用の Label（セッション切替後に更新するため）
     * @param workDir            作業ディレクトリの Path（セッション作成時に使用）
     * @param runtimeManager     セッションランタイムマネージャー（セッション切替時に使用）
     */
    private void configureSessionListCellFactory(
            ListView<SessionSummary> sessionList,
            ConversationStore conversationStore,
            AtomicReference<ChatInteractor> interactorRef,
            WebEngine webEngine,
            Runnable[] refreshSessionsRef,
            Label baseDirLabel,
            Path workDir,
            SessionRuntimeManager runtimeManager) {
        // 履歴行の右クリックで削除できるコンテキストメニューを追加
        sessionList.setCellFactory(lv -> {
            javafx.scene.control.ListCell<SessionSummary> cell = new javafx.scene.control.ListCell<>() {
                @Override
                protected void updateItem(SessionSummary item, boolean empty) {
                    super.updateItem(item, empty);
                    setText(empty || Objects.isNull(item) ? null : item.title());
                }
            };

            javafx.scene.control.MenuItem deleteItem = new javafx.scene.control.MenuItem("削除");
            deleteItem.setOnAction(ev -> {
                deleteSessionAndSwitch(cell.getItem(), conversationStore, interactorRef, webEngine,
                        refreshSessionsRef[0], baseDirLabel, workDir, runtimeManager);
            });

            javafx.scene.control.MenuItem changeTitleItem = new javafx.scene.control.MenuItem("タイトルを変更");
            changeTitleItem.setOnAction(ev -> {
                SessionSummary selected = cell.getItem();
                if (Objects.isNull(selected)) {
                    return;
                }

                TextInputDialog dialog = new TextInputDialog(selected.title());
                dialog.setTitle("タイトル変更");
                dialog.setHeaderText("新しいタイトルを入力してください");
                dialog.setContentText("タイトル:");
                dialog.showAndWait().ifPresent(newTitle -> {
                    SessionRuntime runtime = runtimeManager.getOrCreate(selected.sessionId());
                    if (Objects.isNull(runtime) || Objects.isNull(runtime.getInteractor())) {
                        return;
                    }
                    runtime.getInteractor().changeCurrentSessionTitle(newTitle);
                    if (refreshSessionsRef[0] != null) {
                        refreshSessionsRef[0].run();
                    }
                });
            });

            javafx.scene.control.ContextMenu menu = new javafx.scene.control.ContextMenu(changeTitleItem, deleteItem);
            cell.setContextMenu(menu);
            return cell;
        });
    }

    /**
     * メッセージ送信中の UI 状態に切り替えるユーティリティ。入力欄を無効化し、送信ボタンを「応答中...」に変更するなど。
     * 
     * @param inputField       入力欄の TextArea
     * @param sendButton       送信ボタン
     * @param cancelButton     キャンセルボタン
     * @param progressLabel    進捗表示用の Label
     * @param newChatButton    新規チャットボタン
     * @param deleteChatButton チャット削除ボタン
     */
    private void setSendingUiState(
            TextArea inputField,
            Button sendButton,
            Button cancelButton,
            Label progressLabel,
            Button newChatButton,
            Button deleteChatButton) {
        inputField.setDisable(true);
        sendButton.setDisable(true);
        cancelButton.setDisable(false);
        sendButton.setText("応答中...");
        progressLabel.setVisible(true);
        progressLabel.setManaged(true);
        progressLabel.setText("[進捗] 応答を準備中...");
        newChatButton.setDisable(true);
        // bind中のプロパティは直接setDisableできないためunbindしてから無効化
        deleteChatButton.disableProperty().unbind();
        deleteChatButton.setDisable(true);
    }

    /**
     * メッセージ処理完了後の共通 UI 状態復帰処理。
     * 
     * @param inputField       入力欄の TextArea
     * @param sendButton       送信ボタン
     * @param cancelButton     キャンセルボタン
     * @param progressLabel    進捗表示用の Label
     * @param newChatButton    新規チャットボタン
     * @param deleteChatButton チャット削除ボタン
     * @param sessionList      セッションリストの ListView（削除ボタンの再バインドに使用）
     * @param unused           未使用（互換性のため）
     */
    private void completeMessageHandling(
            TextArea inputField,
            Button sendButton,
            Button cancelButton,
            Label progressLabel,
            Button newChatButton,
            Button deleteChatButton,
            ListView<SessionSummary> sessionList,
            Void unused) {
        restoreIdleUiState(inputField, sendButton, cancelButton, progressLabel, newChatButton,
                deleteChatButton, sessionList);
    }

    /**
     * UI をアイドル状態に戻すユーティリティ。入力欄を有効化し、送信ボタンを「送信」に戻すなど。
     * 
     * @param inputField       入力欄の TextArea
     * @param sendButton       送信ボタン
     * @param cancelButton     キャンセルボタン
     * @param progressLabel    進捗表示用の Label
     * @param newChatButton    新規チャットボタン
     * @param deleteChatButton チャット削除ボタン
     * @param sessionList      セッションリストの ListView（削除ボタンの再バインドに使用）
     */
    private void restoreIdleUiState(
            TextArea inputField,
            Button sendButton,
            Button cancelButton,
            Label progressLabel,
            Button newChatButton,
            Button deleteChatButton,
            ListView<SessionSummary> sessionList) {
        progressLabel.setVisible(false);
        progressLabel.setManaged(false);
        progressLabel.setText("");
        inputField.setDisable(false);
        sendButton.setDisable(false);
        cancelButton.setDisable(true);
        sendButton.setText("送信");
        newChatButton.setDisable(false);
        // bindを再設定して通常動作に戻す
        deleteChatButton.disableProperty().bind(sessionList.getSelectionModel().selectedItemProperty().isNull());
        inputField.requestFocus();
    }

    /**
     * 指定されたセッション ID に切り替える共通ロジック。セッションランタイムから ChatInteractor を取得し、WebView
     * を更新して作業ディレクトリ表示も最新化する。
     * セッション切替後にセッションリストを最新化するための Runnable も呼び出す。
     * 
     * @param runtimeManager  セッションランタイムマネージャー
     * @param interactorRef   現在の ChatInteractor を保持する AtomicReference（切替後に更新するため）
     * @param webEngine       WebView の WebEngine（切替後のプレビュー更新に使用）
     * @param refreshSessions セッションリストを最新化する Runnable（切替後に呼び出すため）
     * @param baseDirLabel    作業ディレクトリ表示用の Label（切替後に更新するため）
     * @param sessionId       切り替えるセッションの ID
     */
    private void switchToSession(
            SessionRuntimeManager runtimeManager,
            AtomicReference<ChatInteractor> interactorRef,
            WebEngine webEngine,
            Runnable refreshSessions,
            Label baseDirLabel,
            String sessionId,
            ConversationStore conversationStore) {

        if (Objects.isNull(sessionId) || sessionId.isBlank()) {
            return;
        }

        SessionRuntime rt = runtimeManager.getOrCreate(sessionId);
        if (Objects.isNull(rt))
            return;

        ChatInteractor selectedInteractor = rt.getInteractor();
        interactorRef.set(selectedInteractor);
        
        // プロバイダー情報を取得
        ConversationSession session = conversationStore.loadByIdOrCreate(sessionId);
        String provider = session.provider();
        
        updateWebPreview(webEngine, selectedInteractor.getTranscript(), provider);
        baseDirLabel.setText("作業ディレクトリ: " + selectedInteractor.getWorkingDirectory().toString());

        safelyRunRefreshSessions(refreshSessions);
    }

    /**
     * セッションを削除し、次に選択すべきセッションへ切り替える共通ロジック。
     * 削除確認ダイアログを表示してユーザーが承認した場合のみ実行する。
     * 
     * @param selected          削除対象のセッション
     * @param conversationStore 会話履歴のストア
     * @param interactorRef     現在の ChatInteractor を保持する AtomicReference（削除後に更新するため）
     * @param webEngine         WebView の WebEngine（削除後のプレビュー更新に使用）
     * @param refreshSessions   セッションリストを最新化する Runnable（削除後に呼び出すため）
     * @param baseDirLabel      作業ディレクトリ表示用の Label（削除後に更新するため）
     * @param workDir           作業ディレクトリのパス
     * @param runtimeManager    セッションランタイムマネージャー
     */
    private void deleteSessionAndSwitch(
            SessionSummary selected,
            ConversationStore conversationStore,
            AtomicReference<ChatInteractor> interactorRef,
            WebEngine webEngine,
            Runnable refreshSessions,
            Label baseDirLabel,
            Path workDir,
            SessionRuntimeManager runtimeManager) {

        if (Objects.isNull(selected))
            return;

        Alert confirm = new Alert(Alert.AlertType.CONFIRMATION);
        confirm.setTitle("履歴の削除");
        confirm.setHeaderText("この会話履歴を削除しますか？");
        confirm.setContentText(selected.title());

        if (confirm.showAndWait().orElse(ButtonType.CANCEL) != ButtonType.OK) {
            return;
        }

        conversationStore.deleteSession(selected.sessionId());

        java.util.List<SessionSummary> remainings = conversationStore.listSessions();
        if (remainings.isEmpty()) {
            ConversationSession created = conversationStore.createNewSession(workDir.toString());
            switchToSession(runtimeManager, interactorRef, webEngine, refreshSessions, baseDirLabel,
                    created.sessionId(), conversationStore);
        } else {
            SessionSummary next = remainings.get(0);
            switchToSession(runtimeManager, interactorRef, webEngine, refreshSessions, baseDirLabel, next.sessionId(), conversationStore);
        }

        safelyRunRefreshSessions(refreshSessions);
    }

    /**
     * refreshSessions を null チェックと例外処理を行いながら安全に実行するヘルパー。
     * 
     * @param refreshSessions 実行する Runnable（null 可）
     */
    private void safelyRunRefreshSessions(Runnable refreshSessions) {
        if (refreshSessions != null) {
            try {
                refreshSessions.run();
            } catch (Exception ignored) {
            }
        }
    }

    /**
     * WebView を会話履歴のプレビュー表示用に更新するユーティリティ。会話履歴テキストを HTML に変換して WebView にロードする。
     * 会話履歴が空の場合は「会話履歴はまだありません」という
     * 
     * @param webEngine  WebView の WebEngine
     * @param transcript 会話履歴のテキスト
     * @param provider プロバイダー ("openai" または "gemini")
     */
    private static void updateWebPreview(WebEngine webEngine, String transcript, String provider) {
        String sanitized = Objects.isNull(transcript) ? "" : transcript;
        sanitized = sanitized.replaceAll("[\uFEFF\u200B\u200C\u200D]", "");
        sanitized = sanitized.replaceAll("[\\p{Cc}&&[^\\r\\n\\t]]", "");

        String body = sanitized.isBlank()
                ? "<p class='empty'>（会話履歴はまだありません）</p>"
                : renderTranscriptHtml(sanitized);
        
        String providerDisplay = "";
        if (provider != null && !provider.isBlank()) {
            providerDisplay = " (" + provider.toUpperCase() + ")";
        }

        String html = """
                                                <!DOCTYPE html>
                                                <html lang='ja'>
                                                <head>
                                                    <meta charset='UTF-8'>
                                                    <style>
                                                        * { -webkit-font-smoothing: antialiased; text-rendering: optimizeLegibility; }
                                                        body {
                                                            font-family: 'Yu Gothic UI', 'Yu Gothic', 'Meiryo', 'Noto Sans JP', 'Consolas', monospace, sans-serif;
                                                            margin: 16px; background: #fafafa; color: #1f2937; font-size: 13px;
                                                        }
                                                        h2 { margin: 0 0 12px 0; font-size: 18px; }
                                                        .panel { background: #fff; border: 1px solid #e5e7eb; border-radius: 10px; padding: 12px; }
                                                        .msg-row { display: flex; align-items: baseline; gap: 6px; margin: 3px 0; }
                                                        .label-you { color: #0066cc; font-weight: 600; white-space: nowrap; }
                                                        .label-assistant { color: #008000; font-weight: 600; white-space: nowrap; }
                                                        .md-content { flex: 1; line-height: 1.6; }
                                                        .md-content > *:first-child { margin-top: 0; }
                                                        .md-content > *:last-child { margin-bottom: 0; }
                                                        .md-content p { margin: 0 0 4px 0; }
                                                        .md-content pre { background: #f3f4f6; border-radius: 4px; padding: 8px; overflow-x: auto; margin: 4px 0; }
                                                        .md-content code { background: #f3f4f6; border-radius: 3px; padding: 1px 4px; font-family: 'Consolas', monospace; font-size: 12px; }
                                                        .md-content pre code { background: none; padding: 0; }
                                                        .md-content ul, .md-content ol { margin: 4px 0; padding-left: 20px; }
                                                        .md-content h1,.md-content h2,.md-content h3 { margin: 8px 0 4px 0; font-size: 14px; }
                                                        .plain-content { flex: 1; white-space: pre-wrap; word-break: break-word; line-height: 1.5; }
                                                        .empty { color: #6b7280; }
                                                        details.tool { margin: 8px 0; border: 1px solid #d1d5db; border-radius: 8px; background: #fcfcfd; }
                                                        details.tool > summary { cursor: pointer; padding: 8px 10px; color: #ff6600; font-weight: 700; user-select: none; }
                                                        details.tool > pre {
                                                            margin: 0; padding: 10px; border-top: 1px solid #e5e7eb;
                                                            white-space: pre-wrap; word-break: break-word; line-height: 1.5; font-size: 13px; background: #fff;
                                                            font-family: 'Yu Gothic UI', 'Yu Gothic', 'Meiryo', 'Consolas', monospace, sans-serif;
                                                        }
                                                    </style>
                                                </head>
                                                <body>
                                                    <h2>会話プレビュー%s</h2>
                                                    <div class='panel'>
                %s
                                                    </div>
                                                    <script>%s</script>
                                                    <script>
                                                        if (typeof marked !== 'undefined') {
                                                            marked.setOptions({ breaks: true });
                                                            document.querySelectorAll('.md-content[data-md]').forEach(function(el) {
                                                                el.innerHTML = marked.parse(el.getAttribute('data-md'));
                                                            });
                                                        }

                                                        // 描画後に最下部へ移動し、最新メッセージを見える位置にする。
                                                        function scrollToBottom() {
                                                            window.scrollTo(0, document.body.scrollHeight);
                                                        }
                                                        requestAnimationFrame(scrollToBottom);
                                                        setTimeout(scrollToBottom, 0);
                                                        setTimeout(scrollToBottom, 50);
                                                    </script>
                                                </body>
                                                </html>
                                                """
                .formatted(providerDisplay, body, MARKED_JS_INLINE);
        webEngine.loadContent(html, "text/html");
    }

    /**
     * `marked.min.js` をリソースから読み込んでインライン JavaScript として返すユーティリティ。
     * 
     * @return `marked.min.js` の内容をインライン JavaScript として返す。読み込みに失敗した場合は空文字列を返す。
     */
    private static String loadMarkedJsInline() {
        try (InputStream in = App.class.getClassLoader().getResourceAsStream("vendor/marked.min.js")) {
            if (Objects.isNull(in)) {
                return "";
            }
            String js = new String(in.readAllBytes(), StandardCharsets.UTF_8);
            return js.replace("</script", "<\\/script");
        } catch (Exception ignored) {
            return "";
        }
    }

    /**
     * 会話履歴のテキストを HTML に変換するユーティリティ。`You: ` と `Assistant: `
     * の行を検出して適切なスタイルを適用し、ツール出力ブロックも `<details>` タグで折りたたみ表示する。
     * 
     * @param transcript 会話履歴のテキスト
     * @return 会話履歴を HTML に変換した文字列
     */
    private static String renderTranscriptHtml(String transcript) {
        String[] lines = transcript.split("\n", -1);
        StringBuilder html = new StringBuilder();

        String currentRole = "NONE"; // YOU, ASSISTANT, NONE
        StringBuilder currentContent = new StringBuilder();
        boolean inToolBlock = false;
        StringBuilder toolContent = new StringBuilder();
        String toolName = "tool";

        for (String line : lines) {
            String normalized = stripChatLabelPrefix(line);
            if (isToolBlockBeginLine(normalized)) {
                if (!"NONE".equals(currentRole) && currentContent.length() > 0) {
                    flushBlock(html, currentRole, currentContent.toString());
                    currentContent.setLength(0);
                    currentRole = "NONE";
                }
                inToolBlock = true;
                toolName = "tool";
                toolContent.setLength(0);
                continue;
            }
            if (isToolBlockEndLine(normalized)) {
                appendToolBlockHtml(html, toolName, toolContent.toString());
                inToolBlock = false;
                toolContent.setLength(0);
                toolName = "tool";
                continue;
            }
            if (inToolBlock) {
                if (toolContent.length() > 0) {
                    toolContent.append("\n");
                }
                toolContent.append(normalized);
                if ("tool".equals(toolName) && isToolResultLine(normalized)) {
                    toolName = extractToolName(normalized);
                }
                continue;
            }

            Matcher youMatcher = YOU_LINE_PATTERN.matcher(line);
            Matcher assistantMatcher = ASSISTANT_LINE_PATTERN.matcher(line);

            if (youMatcher.matches()) {
                if (!"NONE".equals(currentRole) && currentContent.length() > 0) {
                    flushBlock(html, currentRole, currentContent.toString());
                }
                currentRole = "YOU";
                currentContent = new StringBuilder(youMatcher.group(1));
            } else if (assistantMatcher.matches()) {
                if (!"NONE".equals(currentRole) && currentContent.length() > 0) {
                    flushBlock(html, currentRole, currentContent.toString());
                }
                currentRole = "ASSISTANT";
                currentContent = new StringBuilder(assistantMatcher.group(1));
            } else {
                // ★★★ 変更点: ロール判定より先にトークン行を最優先で検出
                if (isTokenInfoLine(line)) {
                    flushBlock(html, currentRole, currentContent.toString());
                    currentRole = "NONE";
                    currentContent.setLength(0);
                    appendTokenInfoLineHtml(html, line);
                } else if (!"NONE".equals(currentRole)) {
                    currentContent.append("\n").append(line);
                } else if (!line.isBlank()) {
                    html.append("<div class='plain-content'>").append(escapeHtml(line)).append("</div>");
                }
            }
        }

        if (inToolBlock && toolContent.length() > 0) {
            appendToolBlockHtml(html, toolName, toolContent.toString());
        } else if (!"NONE".equals(currentRole) && currentContent.length() > 0) {
            flushBlock(html, currentRole, currentContent.toString());
        }
        return html.toString();
    }

    /**
     * 現在のロールとコンテンツを HTML に変換して StringBuilder に追加するユーティリティ。
     * 
     * @param html    HTML を構築する StringBuilder
     * @param role    現在のロール（"YOU" または "ASSISTANT"）
     * @param content ロールに対応するコンテンツのテキスト
     */
    private static void flushBlock(StringBuilder html, String role, String content) {
        if ("YOU".equals(role)) {
            html.append("<div class='msg-row'>")
                    .append("<span class='label-you'>You:</span>")
                    .append("<div class='plain-content'>")
                    .append(escapeHtml(content))
                    .append("</div></div>\n");
        } else if ("ASSISTANT".equals(role)) {
            html.append("<div class='msg-row'>")
                    .append("<span class='label-assistant'>Assistant:</span>")
                    .append("<div class='md-content' data-md='")
                    .append(escapeHtml(content))
                    .append("'></div></div>\n");
        }
    }

    /**
     * ツールの結果ブロックを HTML に変換して StringBuilder に追加するユーティリティ。
     * 
     * @param html     HTML を構築する StringBuilder
     * @param toolName ツールの名前
     * @param content  ツールの結果のコンテンツ
     */
    private static void appendToolBlockHtml(StringBuilder html, String toolName, String content) {
        String visibleName = (Objects.isNull(toolName) || toolName.isBlank()) ? "tool" : toolName;
        html.append("<details class='tool'><summary>")
                .append(escapeHtml(visibleName))
                .append(" の結果</summary><pre>")
                .append(escapeHtml(content))
                .append("</pre></details>");
    }

    /**
     * ツール出力ブロックの開始行かどうかを判定するユーティリティ。`Assistant: (tool:toolName)` または `Assistant:
     * (tool:toolName) result`
     * 
     * @param normalized 正規化済みの行（"Assistant: " プレフィックス削除済み）
     * @return 行がツール出力ブロックの開始行であれば true、そうでなければ false
     */
    private static boolean isToolBlockBeginLine(String normalized) {
        return normalized.equals(TOOL_RESULTS_BEGIN_MARKER);
    }

    /**
     * ツール出力ブロックの終了行かどうかを判定するユーティリティ。`Assistant: (tool:toolName) end` または
     * `Assistant: (tool:toolName) result end`
     * 
     * @param normalized 正規化済みの行（"Assistant: " プレフィックス削除済み）
     * @return 行がツール出力ブロックの終了行であれば true、そうでなければ false
     */
    private static boolean isToolBlockEndLine(String normalized) {
        return normalized.equals(TOOL_RESULTS_END_MARKER);
    }

    /**
     * ツールの結果行かどうかを判定するユーティリティ。`(tool:toolName) result` で始まる行、または `toolName: result`
     * で始まる行。
     * 
     * @param line 判定対象の行
     * @return 行がツールの結果行であれば true、そうでな
     */
    private static boolean isToolResultLine(String line) {
        String normalized = stripChatLabelPrefix(line);
        return normalized.matches("^\\(tool:\\w+\\).*")
                || normalized.matches("^[^\\p{L}\\p{N}\\s(]\\s*\\w+:.*");
    }

    /**
     * ツールの結果行からツール名を抽出するユーティリティ。`(tool:toolName) result` 形式、または `toolName: result`
     * 形式の両方に対応。
     * 
     * @param line ツールの結果行
     * @return 抽出されたツール名。抽出できない場合は "tool" を返す。
     */
    private static String extractToolName(String line) {
        String normalized = stripChatLabelPrefix(line);

        Matcher m1 = TOOL_NAME_PATTERN_1.matcher(normalized);
        if (m1.find()) {
            return m1.group(1);
        }
        Matcher m2 = TOOL_NAME_PATTERN_2.matcher(normalized);
        if (m2.find()) {
            return m2.group(1);
        }
        return "tool";
    }

    /**
     * チャットの発言行から "You: " または "Assistant: " のプレフィックスを削除するユーティリティ。入力が null
     * の場合は空文字列を返す。
     * 
     * @param line 正規化対象の行
     * @return "You: " または "Assistant: " のプレフィックスが削除された行。入力が null の場合は空文字列を返す。
     */
    private static String stripChatLabelPrefix(String line) {
        if (Objects.isNull(line)) {
            return "";
        }
        return line.replaceFirst("^(You|Assistant):\\s+", "");
    }

    /**
     * トークン情報行かどうかを判定するユーティリティ。
     * 「●トークン: input=X output=Y (計Z)」形式の行を検出する。
     * 
     * @param line 判定対象の行
     * @return 行がトークン情報行であれば true
     */
    private static boolean isTokenInfoLine(String line) {
        if (Objects.isNull(line)) {
            return false;
        }
        boolean matches = line.matches("^\\s*●トークン:\\s*input=.*output=.*計.*");
        System.out.println("[DEBUG] isTokenInfoLine check: '" + line + "' -> " + matches);
        return matches;
    }

    /**
     * トークン情報行を HTML で表示する形式に変換して StringBuilder に追加するユーティリティ。
     * 「●トークン: input=X output=Y (計Z)」を `<small>` タグで囲んで表示。
     * 
     * @param html HTML を構築する StringBuilder
     * @param line トークン情報行（例：「●トークン: input=1,234 output=567 (計1,801)」）
     */
    private static void appendTokenInfoLineHtml(StringBuilder html, String line) {
        // 複数ラウンドの場合、改行で分割して各行を処理
        String[] lines = line.split("\n");
        for (String tokenLine : lines) {
            String trimmed = tokenLine.trim();
            if (!trimmed.isEmpty()) {
                System.out.println("[DEBUG] appendTokenInfoLineHtml called with: " + trimmed);
                html.append("<div class='msg-row' style='justify-content: flex-end; margin-top: 8px;'>")
                        .append("<span style='color: #999; font-size: 12px; font-family: monospace; border-left: 2px solid #ddd; padding-left: 8px;'>")
                        .append(escapeHtml(trimmed))
                        .append("</span></div>\n");
            }
        }
    }

    /**
     * HTML の特殊文字をエスケープするユーティリティ。`&`, `<`, `>`, `"`, `'` をそれぞれ対応する HTML
     * エンティティに置換する。
     * 
     * @param text エスケープ対象の文字列
     * @return エスケープ後の文字列。入力が null の場合は空文字列を返す。
     */
    private static String escapeHtml(String text) {
        if (Objects.isNull(text)) {
            return "";
        }
        return text
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }

    /**
     * プロバイダー選択ダイアログを表示して、ユーザーが選択したプロバイダーを返します。
     * キャンセルの場合は null を返します。
     * 設定済みのプロバイダーのみを表示します。
     * 
     * @return 選択されたプロバイダー（"openai" / "gemini"、キャンセル時は null）
     */
    private String showProviderSelectionDialog() {
        java.util.List<String> availableProviders = ChatServiceFactory.getAvailableProviders();
        
        if (availableProviders.isEmpty()) {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("エラー");
            alert.setHeaderText("プロバイダーが設定されていません");
            alert.setContentText("環境変数 MYAGENT2_API_KEY_OPENAI/GEMINI と MYAGENT2_BASE_URL_OPENAI/GEMINI を設定してください。");
            alert.showAndWait();
            return null;
        }

        if (availableProviders.size() == 1) {
            return availableProviders.get(0);
        }

        Dialog<String> dialog = new Dialog<>();
        dialog.setTitle("プロバイダーを選択");
        dialog.setHeaderText("新しいセッションで使用するプロバイダーを選択してください");

        ButtonType selectButtonType = new ButtonType("選択", ButtonBar.ButtonData.OK_DONE);
        dialog.getDialogPane().getButtonTypes().addAll(selectButtonType, ButtonType.CANCEL);

        javafx.scene.control.ComboBox<String> providerCombo = new javafx.scene.control.ComboBox<>();
        
        for (String provider : availableProviders) {
            String displayName = "openai".equals(provider) ? "OpenAI" : "Gemini";
            providerCombo.getItems().add(provider);
        }
        
        if (!providerCombo.getItems().isEmpty()) {
            providerCombo.setValue(providerCombo.getItems().get(0));
        }

        VBox contentBox = new VBox(8);
        contentBox.setPadding(new Insets(16));
        contentBox.getChildren().addAll(
            new Label("プロバイダー:"),
            providerCombo
        );

        dialog.getDialogPane().setContent(contentBox);
        dialog.setResultConverter(bt -> 
            bt == selectButtonType ? providerCombo.getValue() : null
        );

        return dialog.showAndWait().orElse(null);
    }

    /**
     * モデル選択ダイアログを表示して、ユーザーが選択したモデル名を返します。
     * キャンセルの場合は null を返します。
     * 
     * @return 選択されたモデル名（キャンセル時は null）
     * @deprecated プロバイダー選択に移行したため、このメソッドは今後使用されません。
     */
    @Deprecated
    private String showModelSelectionDialog() {
        Dialog<String> dialog = new Dialog<>();
        dialog.setTitle("モデルを選択");
        dialog.setHeaderText("新しいセッションで使用するモデルを選択してください");

        ButtonType selectButtonType = new ButtonType("選択", ButtonBar.ButtonData.OK_DONE);
        dialog.getDialogPane().getButtonTypes().addAll(selectButtonType, ButtonType.CANCEL);

        // 一般的なモデルのリスト
        String[] modelOptions = {
            "gpt-4o-mini",
            "gpt-4o",
            "gpt-4-turbo",
            "gpt-4",
            "claude-3-haiku",
            "claude-3-sonnet",
            "claude-3-opus",
            "o1-mini",
            "o1"
        };

        javafx.scene.control.ComboBox<String> modelCombo = new javafx.scene.control.ComboBox<>();
        modelCombo.getItems().addAll(modelOptions);
        modelCombo.setValue("gpt-4o-mini");
        modelCombo.setEditable(false);

        VBox contentBox = new VBox(8);
        contentBox.setPadding(new Insets(16));
        contentBox.getChildren().addAll(
            new Label("モデル:"),
            modelCombo
        );

        dialog.getDialogPane().setContent(contentBox);
        dialog.setResultConverter(bt -> 
            bt == selectButtonType ? modelCombo.getValue() : null
        );

        return dialog.showAndWait().orElse(null);
    }
}
