/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appClassExists() {
        // App は JavaFX Application のため UI テストは行わず、クラスが存在することのみ確認する
        assertNotNull(App.class);
    }
}
